export const FETCH_SUBMISSIONS_SUCCESS = 'FETCH_SUBMISSIONS_SUCCESS';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const REQUEST_SENT = 'REQUEST_SENT';
export const ADD_SUBREDDIT_SUCCESS ='ADD_SUBREDDIT_SUCCESS';
export const INPUT_SUBREDDIT_WRONG_NAME ='INPUT_SUBREDDIT_WRONG_NAME';
export const WRONG_SUBREDDIT_DUPLICATE_FOUND ='WRONG_SUBREDDIT_DUPLICATE_FOUND';
export const SUBREDDIT_DOES_NOT_EXIST ='SUBREDDIT_DOES_NOT_EXIST';