//export const FETCH_SUBMISSIONS = 'FETCH_SUBMISSIONS'
export const FETCH_SUBMISSIONS_SUCCESS = 'FETCH_SUBMISSIONS_SUCCESS';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
export const REQUEST_SENT = 'REQUEST_SENT';
